#!/usr/bin/env bash

osascript -e 'tell application "Spotify" to next track'

echo -n -e "\033]0;nextTrack\007"

osascript -e 'tell application "Terminal" to close (every window whose name contains "nextTrack")' &

exit 0